#!/usr/bin/env bash
set -euo pipefail

repo_root="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$repo_root"

if ! cargo about --version >/dev/null 2>&1; then
    echo "cargo-about is required; install it with: cargo install cargo-about --locked" >&2
    exit 1
fi

template_file="$(mktemp)"
output_file="$(mktemp)"
trap 'rm -f "$template_file" "$output_file"' EXIT

read -r -d '' template <<'EOF' || true
# Third-party licenses

This file is generated by `scripts/gen-licenses.sh`. Do not edit it manually.

{{#each licenses}}
## {{name}} (`{{id}}`)

Used by:
{{#each used_by}}
- `{{crate.name}} {{crate.version}}`
{{/each}}

```text
{{{text}}}
```

{{/each}}
EOF
printf '%s\n' "$template" >"$template_file"

cargo about generate \
    --features native-backend \
    "$template_file" >"$output_file"

test -s "$output_file"
mv "$output_file" THIRD-PARTY-LICENSES.md
echo "generated $repo_root/THIRD-PARTY-LICENSES.md"
